name: BillingTimeCalc
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    macOS: "13.0"
targets:
  BillingTimeCalc:
    type: application
    platform: macOS
    sources:
      - path: .
        excludes:
          - "*.md"
          - "*.sh"
          - "*.yml"
          - "build"
          - ".git"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.BillingTimeCalc
      INFOPLIST_FILE: Info.plist
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "13.0"
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "66"

